name: Test

on:
  push:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.txt -covermode=count ./...

      - name: Upload coverage to CodeCov
        with:
          file: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Run Go tests
        run: go test ./...
