name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Run Go tests
        run: go test ./...

      - name: Install golint
        run: go get golang.org/x/lint/golint

      - name: Run golint
        run: golint ./... | go run main.go golint
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
